model:
  H: 128
  W: 96
  radius: 1.5
  rad_pow: 2
  pp_pixel: 24
  accumulation: "alphacomposite"

dataset:
  train:
    target: data.gs.DiffData3
    params:
      file_list: 'wildrgb'
      val: False
  val:
    target: data.gs.DiffData3
    params:
      file_list: 'wildrgb'
      val: True

train:
  # experiment directory path
  exp_dir: 'exp'
  learning_rate: 1e-4
  # total batch size
  batch_size: 4
  num_workers: 2
  train_steps: 150000
  log_every: 50
  ckpt_every: 10000
  image_every: 10000
  val_every: 10000
  resume: ~
