model:
  H: 512
  W: 384
  radius: 1.5
  pp_pixel: 24

dataset:
  train:
    target: data.gs.DiffData3
    params:
      file_list: '/scratch/antruong/workspace/myspace/datasets/diff_dataset_train'
      val: False
  val:
    target: data.gs.DiffData3
    params:
      file_list: '/scratch/guachen/datasets/dust3r_pcd_rendered_images'
      val: True

train:
  # experiment directory path
  exp_dir: 'exp'
  learning_rate: 1e-4
  # total batch size
  batch_size: 8
  num_workers: 1
  train_steps: 150000
  log_every: 50
  ckpt_every: 10000
  image_every: 1000
  val_every: 1000
  resume: ~
