model:
  H: 512  # 512
  W: 384  # 
  radius: 1.00
  rad_pow: 2
  pp_pixel: 24
  accumulation: "wsumnorm"

dataset:
  train:
    target: data.gs.DiffData3
    params:
      file_list: 'wildrgb'
      val: False
  val:
    target: data.gs.DiffData3
    params:
      file_list: 'wildrgb'
      val: True

train:
  # experiment directory path
  exp_dir: 'exp'
  learning_rate: 1e-4
  # total batch size
  batch_size: 2
  num_workers: 2
  train_steps: 300000
  log_every: 50
  ckpt_every: 5000
  image_every: 10000
  val_every: 10000
  resume: exp/checkpoints/0010000.pt