model:
  H: 512  # 512
  W: 384  # 
  radius: 1.5 # 1.5
  fradius248: 1
  fradius16: 0.5
  rad_pow: 2
  pp_pixel: 8
  accumulation: "wsumnorm"

dataset:
  train:
    target: data.multi.MultiDataLoader # data.multi.MultiDataset, data.dtu.DTU_Dataset, data.wildrgb.WildRGBDataset
    params:
      file_list: 'datasets' # 'datasets', 'datasets/dtu_down_4', datasets/wildrgb
      batch_size: 4
      shuffle: True
      num_workers: 1
  val:
    target: data.multi.MultiDataLoader
    params:
      file_list: 'datasets'
      batch_size: 4
      shuffle: False
      num_workers: 1

# dataset:
#   train:
#     target: data.multi.MultiDataLoader # data.multi.MultiDataset, data.dtu.DTU_Dataset, data.wildrgb.WildRGBDataset
#     params:
#       file_list: 'datasets' # 'datasets', 'datasets/dtu_down_4', datasets/wildrgb
#       val: False
#   val:
#     target: data.multi.MultiDataLoader
#     params:
#       file_list: 'datasets'
#       val: True

train:
  # experiment directory path
  exp_dir: 'exp'
  learning_rate: 1e-4
  # total batch size
  batch_size: 4
  num_workers: 1
  train_steps: 300000
  log_every: 50
  ckpt_every: 5000
  image_every: 10000
  val_every: 10000
  resume: exp/checkpoints/0065000.pt